name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  pre-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Finding files and store to output
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find ./integration -name '*.go' ! -name '*env_test.go' ! -name '*integration_test.go' -print )"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  integration:
    needs: pre-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-file: ${{fromJson(needs.prep-test.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Starport
        run: go install ./...

      - name: Run Integration Tests
        run: go test -v -timeout 120m ${{ matrix.test-file }} ./integration/env_test.go ./integration/integration_test.go
